version: '3.3'

services:
  assistant_api:
    build:
      context: ./assistant_api
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - assistant-redis
      - postgres
      - es
    ports:
      - "8000:8000"

  assistant_nginx:
    image: nginx:latest
    container_name: assistant_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_config:/etc/nginx/conf.d:ro
      - nginx_log:/var/log/nginx/
    depends_on:
      - assistant_api
    ports:
      - "84:84"
    networks:
      - my_network

  assistant-redis:
    image: redis:latest
    container_name: assistant-redis
    restart: always
    networks:
      - my_network
    env_file:
      - .env
    ports:
      - "6379:6379"

  etl:
    container_name: assistant-etl
    restart: unless-stopped
    build: ./etl
    env_file:
      - .env
    depends_on:
      - postgres
      - es
    networks:
      - my_network

  postgres:
    image: postgres:13
    container_name: assistant-postgres
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/data/postgres
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME:-movies_database}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - my_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: assistant-es
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
    ports:
      - "9200:9200"
    networks:
      - my_network

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - my_network

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - nginx_log:/var/log/nginx
    command: -config.file=/etc/promtail/config.yml
    networks:
      - my_network

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - my_network
  assistant_tests:
    build: ./tests/functional
    container_name: assistant_tests
    depends_on:
      - assistant_api
      - assistant-redis
      - etl
    env_file:
      - .env
    networks:
      - my_network

volumes:
  nginx_log:
networks:
  my_network:
    external: True
