version: '3.3'

services:
  assistant_api:
    build:
      context: ./assistant_api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./infra/nlp_models:/src/api/nlp_models:ro
    networks:
      - my_network
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    depends_on:
      - assistant-redis
      - postgres
      - es

  assistant_nginx:
    image: nginx:1.26.1
    container_name: assistant_nginx
    restart: unless-stopped
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/nginx_config:/etc/nginx/conf.d:ro
    depends_on:
      - assistant_api
    ports:
      - "84:84"
    networks:
      - my_network

  assistant-redis:
    image: redis:latest
    container_name: assistant-redis
    restart: unless-stopped
    networks:
      - my_network
    env_file:
      - .env

  etl:
    container_name: assistant-etl
    restart: unless-stopped
    build: ./etl
    env_file:
      - .env
    depends_on:
      - postgres
      - es
    networks:
      - my_network

  postgres:
    image: postgres:16-alpine
    container_name: assistant-postgres
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/data/postgres
      - ./infra/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME:-movies_database}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - my_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: assistant-es
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - my_network

  assistant_tests:
    build: assistant_api/tests/functional
    container_name: assistant_tests
    restart: unless-stopped
    depends_on:
      - assistant_api
      - assistant-redis
      - etl
    env_file:
      - .env
    networks:
      - my_network

volumes:
  data:

networks:
  my_network:
    external: True
