version: '3.8'

services:
  assistant_api:
    build:
      context: ./assistant_api
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
        - assistant-redis
    ports:
      - "8000:8000"

  assistant-redis:
    image: redis:latest
    container_name: assistant-redis
    restart: always
    networks:
      - my_network
    env_file:
      - .env
    ports:
      - "6379:6379"

  etl:
    container_name: assistant-etl
    restart: unless-stopped
    build: ./etl
    env_file:
      - .env
    depends_on:
      - postgres
      - es
    networks:
      - my_network

  postgres:
    image: postgres:13
    container_name: assistant-postgres
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/data/postgres
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME:-movies_database}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - my_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: assistant-es
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
    ports:
      - "9200:9200"
    networks:
      - my_network
      
networks:
  my_network:
    external: True
