version: '3.8'

services:
  # assistant_api:
  #   build:
  #     context: ./assistant_api
  #   env_file:
  #     - .env
  #   networks:
  #     - my_network
  #   depends_on:
  #       - redis
  #   ports:
  #     - "8000:8000"

  assistant-redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"

networks:
  my_network:
    external: True
