@startuml
!theme materia

title  АРХИТЕКТУРА ТO BE

agent Клиент

node "Assistant" as assistant {
    component "ASSISTANT_API" as api
    component "Custom LLM" as llm
    database "cache" as cache
    }

component TTS
database Elastic
component STT

Клиент --> STT: голосовой запрос
api <--> Elastic: поисковой запрос
api <--> cache: контекст сообщения
api --> TTS: ответ для прочтения
api <--> llm: анализ текста
TTS --> Клиент

@enduml